name: mind-nlp-deep-cpu
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.23
  - scipy=1.10.1
  - pandas=1.5
  - matplotlib=3.7
  - openpyxl
  - scikit-learn=1.2
  - networkx=3.1
  - jupyterlab
  - ipykernel
  - pytorch=2.1
  - torchvision=0.16
  - torchaudio=2.1
  - cpuonly
  - pip
  - pip:
      - gensim==4.3.0
      - kiwipiepy
      - tokenizers==0.15.0
      - transformers==4.36.2
      - datasets==2.14.6